---
- name: Install nginx dependency packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ NGINX_DEPENDENCY_PACKAGES }}"

- include: ../../common/tasks/create_nginx_user.yml

- name: Create nginx temp directory
  file:
    path: "{{ NGINX_TEMP_DIR }}"
    state: directory
    mode: "0755"

- name: Create nginx log directory
  file:
    path: "{{ NGINX_LOG_DIR }}"
    state: directory
    mode: "0755"

- name: Copy nginx tarball
  copy:
    src: "{{ NGINX_BASENAME }}.tar.gz"
    dest: "{{ SRC_DIR }}"

- name: Decompress nginx tarball
  unarchive:
    remote_src: yes
    src: "{{ SRC_DIR }}/{{ NGINX_BASENAME }}.tar.gz"
    dest: "{{ SRC_DIR }}"
    creates: "{{ SRC_DIR }}/{{ NGINX_BASENAME }}"

- name: Check nginx compilation flags
  template:
    src: .nginx_compilation_flags.j2
    dest: "{{ SRC_DIR }}/{{ NGINX_BASENAME }}/.nginx_compilation_flags"
  register: nginx_compilation_flags

- name: Run nginx configure script
  command: "./configure {{ NGINX_CONFIGURE_OPTIONS | join(' ') }}"
  args:
    chdir: "{{ SRC_DIR }}/{{ NGINX_BASENAME }}"
  when: nginx_compilation_flags.changed

- name: Build nginx
  make:
    chdir: "{{ SRC_DIR }}/{{ NGINX_BASENAME }}"
    target: build
  when: nginx_compilation_flags.changed
  register: nginx_build

- name: Install nginx
  make:
    chdir: "{{ SRC_DIR }}/{{ NGINX_BASENAME }}"
    target: install
  when: nginx_build.changed
  notify: Restart nginx

- name: Set nginx symbolic link
  file:
    src: "{{ NGINX_PREFIX }}/sbin/nginx"
    dest: /usr/sbin/nginx
    state: link

- name: Set nginx.service for systemd
  template:
    src: nginx.service.j2
    dest: /lib/systemd/system/nginx.service
  notify: Restart nginx
