---
MYSQL_BASENAME: "mysql-5.7.17-linux-glibc2.5-x86_64"

MYSQL_PREFIX: "{{ PREFIX }}/mysql"

MYSQL_DEPENDENCY_PACKAGES:
  - libaio1

MYSQL_BIN_ENTRIES:
  - innochecksum
  - lz4_decompress
  - myisamchk
  - myisam_ftdump
  - myisamlog
  - myisampack
  - my_print_defaults
  - mysql
  - mysqladmin
  - mysqlbinlog
  - mysqlcheck
  - mysql_client_test_embedded
  - mysql_config
  - mysql_config_editor
  - mysqld
  - mysqld-debug
  - mysqld_multi
  - mysqld_safe
  - mysqldump
  - mysqldumpslow
  - mysql_embedded
  - mysqlimport
  - mysql_install_db
  - mysql_plugin
  - mysqlpump
  - mysql_secure_installation
  - mysqlshow
  - mysqlslap
  - mysql_ssl_rsa_setup
  - mysqltest_embedded
  - mysql_tzinfo_to_sql
  - mysql_upgrade
  - mysqlxtest
  - perror
  - replace
  - resolveip
  - resolve_stack_dump
  - zlib_decompress
