
NGINX_VERSION: nginx-1.11.8
NGINX_SRC_DIR: "{{ SRC_DIR }}/{{ NGINX_VERSION }}"

NGINX_PREFIX: "{{ INSTALL_DIR }}/nginx"
NGINX_CONF_PATH: "{{ NGINX_PREFIX }}/conf/nginx.conf"
NGINX_LOG_DIR: /var/log/nginx
NGINX_TEMP_DIR: /var/lib/nginx

NGINX_DEPENDENCY_PACKAGES_APT:
  - libpcre3-dev
  - libssl-dev
  - libxslt1-dev
  - libgd-dev
  - libgeoip-dev

NGINX_CONFIGURE_OPTIONS:
  - --user={{ NGINX_USER }}
  - --group={{ NGINX_GROUP }}
  - --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2'
  - --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now'
  - --prefix={{ NGINX_PREFIX }}
  - --conf-path={{ NGINX_CONF_PATH }}
  - --http-log-path={{ NGINX_LOG_DIR }}/access.log
  - --error-log-path={{ NGINX_LOG_DIR }}/error.log
  - --lock-path=/var/lock/nginx.lock
  - --pid-path=/run/nginx.pid
  - --http-client-body-temp-path={{ NGINX_TEMP_DIR }}/body
  - --http-fastcgi-temp-path={{ NGINX_TEMP_DIR }}/fastcgi
  - --http-proxy-temp-path={{ NGINX_TEMP_DIR }}/proxy
  - --http-scgi-temp-path={{ NGINX_TEMP_DIR }}/scgi
  - --http-uwsgi-temp-path={{ NGINX_TEMP_DIR }}/uwsgi
  - --with-debug
  - --with-pcre-jit
  - --with-http_ssl_module
  - --with-http_stub_status_module
  - --with-http_realip_module
  - --with-http_auth_request_module
  - --with-http_addition_module
  - --with-http_dav_module
  - --with-http_geoip_module
  - --with-http_gunzip_module
  - --with-http_gzip_static_module
  - --with-http_image_filter_module
  - --with-http_v2_module
  - --with-http_sub_module
  - --with-http_xslt_module
  - --with-stream
  - --with-stream_ssl_module
  - --with-mail
  - --with-mail_ssl_module
  - --with-threads