---
# 参照: https://dev.mysql.com/doc/refman/5.7/en/linux-installation-debian.html

- name: Install mysql dependency packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ MYSQL_DEPENDENCY_PACKAGES }}"

- name: Upload mysql deb bundle
  synchronize:
    src: "{{ role_path }}/files/{{ MYSQL_DEB_BUNDLE_BASENAME }}.tar"
    dest: "{{ SRC_DIR }}/{{ MYSQL_DEB_BUNDLE_BASENAME }}.tar"

- name: Create mysql deb directory
  file:
    path: "{{ SRC_DIR }}/{{ MYSQL_DEB_BUNDLE_BASENAME }}"
    state: directory

- name: Unarchive mysql tarball
  unarchive:
    remote_src: yes
    src: "{{ SRC_DIR }}/{{ MYSQL_DEB_BUNDLE_BASENAME }}.tar"
    dest: "{{ SRC_DIR }}/{{ MYSQL_DEB_BUNDLE_BASENAME }}"
  register: mysql_unarchive_flags

- name: Preconfigure the MySQL server package
  command: "dpkg-preconfigure -f noninteractive mysql-community-server_5.7.17-1ubuntu16.04_amd64.deb"
  args:
    chdir: "{{ SRC_DIR }}/{{ MYSQL_DEB_BUNDLE_BASENAME }}"
  when: mysql_unarchive_flags.changed

- name: Install MySQL server
  command: "dpkg -i {{ MYSQL_DEBS | join(' ') }}"
  args:
    chdir: "{{ SRC_DIR }}/{{ MYSQL_DEB_BUNDLE_BASENAME }}"
  when: mysql_unarchive_flags.changed
