---
# see: http://dev.mysql.com/doc/refman/5.7/en/binary-installation.html

- name: Install mysql dependency packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ MYSQL_DEPENDENCY_PACKAGES }}"

- name: Create mysql group
  group:
    name: "{{ MYSQL_GROUP }}"
    gid: "{{ MYSQL_USER_GID }}"

- name: Create mysql user
  user:
    name: "{{ MYSQL_USER }}"
    uid: "{{ MYSQL_USER_UID }}"
    group: "{{ MYSQL_USER }}"
    system: yes
    shell: /sbin/nologin

- name: Upload mysql tarball
  synchronize:
    src: "{{ MYSQL_BASENAME }}.tar.gz"
    dest: "{{ SRC_DIR }}/{{ MYSQL_BASENAME }}.tar.gz"

- name: Unarchive mysql tarball
  unarchive:
    remote_src: yes
    src: "{{ SRC_DIR }}/{{ MYSQL_BASENAME }}.tar.gz"
    dest: "{{ PREFIX }}"
    creates: "{{ PREFIX }}/{{ MYSQL_BASENAME }}"
  register: mysql_unarchive_flags
  notify: Restart mysqld

- name: Create mysql directory symlink
  file:
    src: "{{ PREFIX }}/{{ MYSQL_BASENAME }}"
    dest: "{{ MYSQL_PREFIX }}"
    state: link

- name: Create mysql bin entries symlink
  file:
    src: "{{ MYSQL_PREFIX }}/bin/{{ item }}"
    dest: "{{ BIN_DIR }}/{{ item }}"
    state: link
  with_items: "{{ MYSQL_BIN_ENTRIES }}"

- name: Set mysqld.service for systemd
  template:
    src: mysqld.service.j2
    dest: /lib/systemd/system/mysqld.service
  notify: Restart mysqld

- name: Create mysql-files directory
  file:
    path: "{{ PREFIX }}/{{ MYSQL_BASENAME }}/mysql-files"
    mode: "0750"
    state: directory
  when: mysql_unarchive_flags.changed

- name: Change mysql directory filemode
  file:
    recurse: yes
    path: "{{ PREFIX }}/{{ MYSQL_BASENAME }}"
    owner: "{{ MYSQL_USER }}"
    group: "{{ MYSQL_GROUP }}"
  when: mysql_unarchive_flags.changed

- name: Initialize mysql
  command: "{{ PREFIX }}/{{ MYSQL_BASENAME }}/bin/mysqld --initialize-insecure --user=mysql"
  when: mysql_unarchive_flags.changed

- name: Execute mysql_ssl_rsa_setup
  command: "{{ PREFIX }}/{{ MYSQL_BASENAME }}/bin/mysql_ssl_rsa_setup"
  when: mysql_unarchive_flags.changed

- name: Change mysql directory owner to root
  file:
    recurse: yes
    path: "{{ PREFIX }}/{{ MYSQL_BASENAME }}"
    owner: root
    group: root
  when: mysql_unarchive_flags.changed

- name: Change mysql directory owner to mysql
  file:
    recurse: yes
    path: "{{ PREFIX }}/{{ MYSQL_BASENAME }}/{{ item }}"
    owner: "{{ MYSQL_USER }}"
    group: "{{ MYSQL_GROUP }}"
  with_items:
    - data
    - mysql-files
  when: mysql_unarchive_flags.changed
