---
- name: Copy php tarball
  copy:
    src: "{{ PHP_BASENAME }}.tar.gz"
    dest: "{{ SRC_DIR }}"

- name: Decompress php tarball
  unarchive:
    src: "{{ SRC_DIR }}/{{ PHP_BASENAME }}.tar.gz"
    dest: "{{ SRC_DIR }}"
    copy: no

- name: Check php compilation flags
  template:
    src: .php_compilation_flags.j2
    dest: "{{ SRC_DIR }}/{{ PHP_BASENAME }}/.php_compilation_flags"
  register: php_compilation_flags

- name: Run php configure script
  command: "./configure {{ PHP_CONFIGURE_OPTIONS | join(' ') }}"
  args:
    chdir: "{{ SRC_DIR }}/{{ PHP_BASENAME }}"
  when: php_compilation_flags.changed

- name: Build php
  make:
    chdir: "{{ SRC_DIR }}/{{ PHP_BASENAME }}"
    target: all
  when: php_compilation_flags.changed
  register: php_build

- name: Install php
  make:
    chdir: "{{ SRC_DIR }}/{{ PHP_BASENAME }}"
    target: install
  when: php_build.changed

- name: Set php.ini
  template:
    src: php.ini-development.j2
    dest: "{{ PHP_PREFIX }}/lib/php.ini"

- name: Create php bin entries symlink
  file:
    src: "{{ PHP_PREFIX }}/bin/{{ item }}"
    dest: "{{ BIN_DIR }}/{{ item }}"
    state: link
  with_items: "{{ PHP_BIN_ENTRIES }}"

- name: Create php sbin entries symlink
  file:
    src: "{{ PHP_PREFIX }}/sbin/{{ item }}"
    dest: "{{ SBIN_DIR }}/{{ item }}"
    state: link
  with_items: "{{ PHP_SBIN_ENTRIES }}"
