- name: Copy php tarball
  copy:
    src: "{{ PHP_VERSION }}.tar.gz"
    dest: "{{ SRC_DIR }}"
    owner: root
    group: root
    mode: "0644"

- name: Decompress php tarball
  unarchive:
    src: "{{ SRC_DIR }}/{{ PHP_VERSION }}.tar.gz"
    dest: "{{ SRC_DIR }}"
    copy: no
    group: root
    owner: root
    mode: "0755"

- name: Run php configure script
  command: "./configure {{ PHP_CONFIGURE_OPTIONS | join(' ') }}"
  args:
    chdir: "{{ PHP_SRC_DIR }}"

- name: Build php
  make:
    chdir: "{{ PHP_SRC_DIR }}"
    target: build
  register: php_build

- name: Install php
  make:
    chdir: "{{ PHP_SRC_DIR }}"
    target: install
  when: php_build.changed
