---
- include: ../../common/tasks/create_nginx_user.yml

- name: Set php-fpm.service
  template:
    src: php-fpm.service.j2
    dest: /etc/systemd/system/php-fpm.service
  register: nginx_compilation_flags

