---
- hosts: tsurami-local
  become: yes
  become_user: root
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/accounts.yml
  roles:
#    - ../roles/nginx
    - ../roles/mysql
#    - ../roles/php
