PHP_VERSION: php-7.1.0
PHP_SRC_DIR: "{{ SRC_DIR }}/{{ PHP_VERSION }}"

PHP_DEPENDENCY_PACKAGES_APT:
  - libxml2-dev

PHP_CONFIGURE_OPTIONS:
  - --prefix=/usr/local/php
  - --enable-phpdbg
  - --enable-fpm
  - --enable-mbstring
  - --disable-cgi
  - --with-pdo-mysql=mysqlnd
