---
PHP_BASENAME: php-7.1.0

PHP_PREFIX: "{{ PREFIX }}/php"

PHP_DEPENDENCY_PACKAGES_APT:
  - libxml2-dev

PHP_CONFIGURE_OPTIONS:
  - --prefix=/usr/local/php
  - --enable-phpdbg
  - --enable-fpm
  - --disable-cgi
  - --with-pdo-mysql=mysqlnd

PHP_BIN_ENTRIES:
  - pear
  - peardev
  - pecl
  - phar
  - phar.phar
  - php
  - php-config
  - phpdbg
  - phpize

PHP_SBIN_ENTRIES:
  - php-fpm
